In [2]:
 #1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))

# Interchange rows and columns (transpose the array)
transposed_array = array.T

print("Original Array:")
print(array)

print("\nTransposed Array:")
print(transposed_array)

Original Array:
[[90 11 67]
 [89 57 22]
 [32 96 40]]

Transposed Array:
[[90 89 32]
 [11 57 96]
 [67 22 40]]


In [7]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

import numpy as np

# Generate a 1D NumPy array with 10 elements
one_d_array = np.arange(10)

# Reshape the 1D array into a 2x5 array
array_2x5 = one_d_array.reshape(2, 5)

# Reshape the 2x5 array into a 5x2 array
array_5x2 = array_2x5.reshape(5, 2)

print("Original 1D Array:")
print(one_d_array)

print("\nReshaped into 2x5 Array:")
print(array_2x5)

print("\nReshaped into 5x2 Array:")
print(array_5x2)

Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped into 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped into 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [8]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

import numpy as np

# Create a 4x4 NumPy array with random float values
array_4x4 = np.random.rand(4, 4)

# Add a border of zeros around it, resulting in a 6x6 array
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("Original 4x4 Array:")
print(array_4x4)

print("\nArray with Zero Border (6x6 Array):")
print(array_6x6)

Original 4x4 Array:
[[0.07353912 0.72240075 0.74286873 0.99766176]
 [0.2630465  0.19784539 0.14934582 0.68211285]
 [0.00868365 0.81892197 0.0519869  0.16465772]
 [0.29628607 0.05220811 0.68097805 0.99298273]]

Array with Zero Border (6x6 Array):
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.07353912 0.72240075 0.74286873 0.99766176 0.        ]
 [0.         0.2630465  0.19784539 0.14934582 0.68211285 0.        ]
 [0.         0.00868365 0.81892197 0.0519869  0.16465772 0.        ]
 [0.         0.29628607 0.05220811 0.68097805 0.99298273 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [10]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array_step = np.arange(10, 65, 5)

print(array_step)

[10 15 20 25 30 35 40 45 50 55 60]


In [11]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations(uppercase, lowercase, title case, etc.) to each element.

import numpy as np

# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_arr = np.char.upper(arr)
lowercase_arr = np.char.lower(arr)
titlecase_arr = np.char.title(arr)
capitalize_arr = np.char.capitalize(arr)

print("Original Array:", arr)
print("Uppercase:", uppercase_arr)
print("Lowercase:", lowercase_arr)
print("Title Case:", titlecase_arr)
print("Capitalize:", capitalize_arr)


Original Array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']
Capitalize: ['Python' 'Numpy' 'Pandas']


In [12]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

import numpy as np

# Create a NumPy array of words
words = np.array(['python', 'numpy', 'data', 'science'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', words)

print("Original Array:", words)
print("Array with spaces between characters:", spaced_words)


Original Array: ['python' 'numpy' 'data' 'science']
Array with spaces between characters: ['p y t h o n' 'n u m p y' 'd a t a' 's c i e n c e']


In [13]:
#7.  Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)


Addition:
 [[ 8 10 12]
 [14 16 18]]
Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [14]:
#8.  Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

print("Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)


Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


In [15]:
#9.  Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Function to check for prime numbers
def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

print("Random Integers:", random_integers)
print("Prime Numbers:", prime_numbers)


Random Integers: [759 340 473 498  61   0 564 694 913 379 247 684 581 499 551 275 826 602
  96 693 514 946 227 927 303 237 614 883   2  84 560 279 444 982 414 791
 332 401 580 595 446 207  65 305  47 132 908 530 229 751 742 517 343 829
 574 623 799 509 409  14 235 676 667 243 971 390 157 141 569 734 316 862
 233 340 817 919 169 958 887 800 429 373 215 718 263 486 622 892 896 200
 893 219 294 667 542 829 977 340 932 189]
Prime Numbers: [61, 379, 499, 227, 883, 2, 401, 47, 229, 751, 829, 509, 409, 971, 157, 569, 233, 919, 887, 373, 263, 829, 977]


In [17]:
#10.  Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
# For simplicity, let's generate random temperatures between 15 and 35 degrees Celsius
daily_temperatures = np.random.randint(15, 36, size=30)

# Calculate weekly averages
# We can calculate the average for the first 28 days and handle the last 2 days separately
weekly_averages = []
for i in range(0, len(daily_temperatures), 7):
    weekly_avg = daily_temperatures[i:i+7].mean()
    weekly_averages.append(weekly_avg)

# Display the daily temperatures and weekly averages
print("Daily Temperatures for the Month:", daily_temperatures)
print("Weekly Averages:", weekly_averages)


Daily Temperatures for the Month: [23 29 34 33 16 23 22 27 32 32 17 15 22 27 33 29 29 23 16 28 30 30 30 31
 16 18 30 29 33 28]
Weekly Averages: [25.714285714285715, 24.571428571428573, 26.857142857142858, 26.285714285714285, 30.5]
